spring:
  application:
    name: driver-finance-app

  datasource:
    url: jdbc:h2:mem:driver_finance_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

logging:
  level:
    root: info                  # Nivel global
    com.baersolutions: debug   # Tu app (más detalle)
    org.hibernate.SQL: debug   # Ver queries SQL
    org.hibernate.orm.jdbc.bind: trace  # Ver parámetros de queries

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"